### ISSUE TITLE
Font on the landing page aren't in proper contrast with the background

### ISSUE THREAD

**Issue by first-brick** [first-brick/landing-website#10]
Change the font colour, change the background. Play around. Use imagination. Feel free.

**Comment by MansiAyer** [comment]
hi, may I take on this?

**Comment by first-brick** [comment]
Sure. Go ahead.

**Comment by MansiAyer** [comment]
👍thanks! On it

**Comment by pradipta** [comment]
@MansiAyer any update on this?

**Comment by MeghalBisht** [comment]
@MansiAyer if you are no longer working on this can I take it @first-brick ?

**Comment by MeghalBisht** [comment]
@pradipta can I go for this as well if @MansiAyer  is not working on it?

**Comment by MansiAyer** [comment]
@MeghalBisht yeah go ahead, I got a few assignments from college on Sat so I had to stop whatever I was doing to finish that first.

**Comment by MansiAyer** [comment]
@pradipta I'm really sorry but I got some assignments from college and got tied up with that. I was hoping it would be okay if I update with whatever I've done by Monday afternoon, again I'm sorry about the delay!

**Comment by first-brick** [comment]
Not a problem. Take your time.
