### ISSUE TITLE
Change Debanga and Gaurav's photo

### ISSUE THREAD

**Issue by first-brick** [first-brick/landing-website#18]
Debanga:
![WhatsApp Image 2020-09-23 at 11 38 10 AM](https://user-images.githubusercontent.com/72573174/95606724-631b0300-0a78-11eb-90d6-1e15fed58f36.jpeg)

Gaurav:
![WhatsApp Image 2020-10-09 at 9 45 41 PM](https://user-images.githubusercontent.com/72573174/95607060-d15fc580-0a78-11eb-9dd7-ef9e60da6636.jpeg)

**Comment by pradipta** [comment]
On it
