### ISSUE TITLE
add a projects page that will have thumbnails of a few projects and clicking on them will open a new view

### ISSUE THREAD

**Issue by first-brick** [first-brick/landing-website#3]

**Comment by MeghalBisht** [comment]
Hello, may I take this?

**Comment by first-brick** [comment]
@MeghalBisht Sure. Go on. Discuss with @pradipta for things you want to know about.

**Comment by MeghalBisht** [comment]
Thanks, @pradipta please let me know more about this issue. Do we need cards for each project?

**Comment by pradipta** [comment]
I dont have a lot of idea around frontend stuff.
Can you check if you can have something like: http://www.zerund.com/projects?
What I want it:
1. The side menu should have "Projects"
2. Clicking on it should open a section, just like it opens the Who We Are section. Basically, I want the side menu to be there. You can play around however you want. If you want to pull the side menu out as a common view mess around, it's great. It's your call.
3. We probably can have around 6 projects in a page. Clicking on each could probably open up an transparent overlay with a number of photos for each. Clicking outside the photo will close it.
4. Pagination would be a good to have thing.

You can take your time with this. Probably break it down into smaller pieces and ship one by one. You can always reach out for help. I hope this is making things clear, let me know if not.

**Comment by MeghalBisht** [comment]
Sounds good. Working on it, will update.

**Comment by MeghalBisht** [comment]
@pradipta Please refer the pull request and let me know about it.
Thanks

**Comment by first-brick** [comment]
@MeghalBisht Thanks for the PR. Closing the issue
