### ISSUE TITLE
Fix Linkedin and Twitter link for Debanga and Gaurav

### ISSUE THREAD

**Issue by first-brick** [first-brick/landing-website#4]

**Comment by first-brick** [comment]
Gaurav:
Linkedin:
Twitter:
Instagram:
Facebook:

Debanga:
Linkedin: https://www.linkedin.com/in/debanga-sarma-959a59107/
Twitter: https://twitter.com/DebangaSarma
Facebook:

Add the contacts cards for the available links. Links for Pradipta are correct and are repeated across the other two.

**Comment by amohapatra123** [comment]
can I work on this issue?

**Comment by first-brick** [comment]
Sure. Have @pradipta review it

**Comment by amohapatra123** [comment]
Links for Debang are mentioned kindly mention links for Gaurav

**Comment by first-brick** [comment]
@pradipta please look into it.

- [x] please look into it.

**Comment by pradipta** [comment]
**Gaurav:**
Linkedin: https://www.linkedin.com/in/ar-gaurav-das-101b65111/
Instagram: https://www.instagram.com/gd_architect_/
Facebook: https://www.facebook.com/Gaurav.28.gca

**Debanga:**
Linkedin: https://www.linkedin.com/in/debanga-sarma-959a59107/
Twitter: https://twitter.com/DebangaSarma
Instagram: instagram.com/debanga.sarma

~Also need to verify/add the links for the Firm on the contact page:
Instagram: https://instagram.com/first_brick_arch_engr
Remove the ones where we do not have a link
If you want, I can have another issue created for this and have it assigned to you.~

**Comment by amohapatra123** [comment]
sure you can create a separate issue and assign it to me

**Comment by pradipta** [comment]
https://github.com/first-brick/landing-website/issues/12

**Comment by amohapatra123** [comment]
I have made the PR you can review and merge it.@pradipta

**Comment by amohapatra123** [comment]
#17

**Comment by first-brick** [comment]
Thanks @amohapatra123 . Closing the issue. Feel free to raise issues for improvements

**Comment by amohapatra123** [comment]
If you can lable a hactoberfest-accepted
